# Generated by Django 4.2.10 on 2024-06-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='Unnamed', max_length=150),
        ),
    ]
